version: '3.8'

services:
  web:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    # volumes:
    #   - .:/app

# volumes:
#   db_data:
