name: Deploy Company Service With Docker

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          
          rm -rf ~/company || true
          git clone https://github.com/DevDevProject/company-service.git ~/company
          cd ~/company

          cat > .env << 'EOT' 
          ${{ secrets.DOTENV_FILE }} 
          EOT

          docker-compose down || true
          docker-compose build
          docker-compose up -d
        EOF
